; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin]
platform = espressif32
framework = arduino
monitor_speed = 115200
board = lolin32
upload_port = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
monitor_port = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags =
    -D HW_LOLIN
    -D TEM_OLED
    -D ASYNCWEBSERVER_REGEX
lib_deps =
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.4.0
    arduino-libraries/NTPClient@^3.2.1
    esp32async/ESPAsyncWebServer
    esp32async/AsyncTCP
    bblanchon/ArduinoJson
    adafruit/Adafruit AHTX0
    claws/BH1750
    adafruit/RTClib@^2.1.4

[env:c3_mini]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board = esp32-c3-devkitm-1
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_DC:06:75:69:07:20-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_DC:06:75:69:07:20-if00
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags = 
    -D HW_C3MINI
    -D ASYNCWEBSERVER_REGEX
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    arduino-libraries/NTPClient@^3.2.1
    esp32async/ESPAsyncWebServer
    esp32async/AsyncTCP
    bblanchon/ArduinoJson
    adafruit/Adafruit AHTX0
    claws/BH1750
    adafruit/RTClib@^2.1.4

[env:esp32]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board = esp32dev
upload_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_5A77055597-if00
monitor_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_5A77055597-if00
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags = 
    -D HW_ESP32
    -D ASYNCWEBSERVER_REGEX
lib_deps =
    arduino-libraries/NTPClient@^3.2.1
    esp32async/ESPAsyncWebServer
    esp32async/AsyncTCP
    bblanchon/ArduinoJson
    adafruit/Adafruit AHTX0
    claws/BH1750
    adafruit/RTClib@^2.1.4
